logconfig:
  path: /Users/reimuwang/temp
  name: file-management

server:
  port: 8080

reimuwang:
  rootDirs: /Users/reimuwang/Downloads/test1;/Users/reimuwang/Downloads/test2
  fileMove:
    sourceDirs: /Users/reimuwang/Downloads/test1;/Users/reimuwang/Downloads/test3
    targetDirs: /Users/reimuwang/Downloads/test2;/Users/reimuwang/Downloads/test4
    prefix: mm
    errorLogIntervalSecond: 5