logconfig:
  path: /Users/reimuwang/temp
  name: file-management

reimuwang:
  rootDirs: /Users/reimuwang/Downloads/test1;/Users/reimuwang/Downloads/test2
  fileMove:
    sourceDir: /Users/reimuwang/Downloads/test1
    targetDir: /Users/reimuwang/Downloads/test2
    markPrefix: m
    errorLogIntervalSecond: 5